[book]
authors = ["Ulyssa"]
language = "en"
multilingual = false
src = "src"
title = "iamb documentation"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/ulyssa/iamb"
cname = "iamb.chat"
additional-css = ["theme/css/custom.css"]
